name: Build and Deploy WAR to Tomcat

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build WAR
        run: mvn clean package -DskipTests

      # Step to list files in the target directory
      - name: List target directory
        run: ls -la target/

       # Step to save WAR file as an artifact
      - name: Save WAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app  # Name of the artifact
          path: target/*.war     # Path to the WAR file


# stop tomcat  --> ps -e

   #   - name: Backup running WAR file
    #    run: |
     #     BACKUP_DIR="/home/varshini/war-backups" 
     #     mkdir -p $BACKUP_DIR

          # Remove the previous backup if it exists
      #    rm -f $BACKUP_DIR/demo-1.0.0-*.war

          # Define a timestamp for the new backup
       #   TIMESTAMP=$(date +%Y%m%d%H%M%S)

          # Backup the currently deployed WAR file from Tomcat webapps directory to the backup folder
        #  cp /home/varshini/tomcat/webapps/demo-1.0.0.war $BACKUP_DIR/demo-1.0.0-$TIMESTAMP.war

         # echo "Backup of running WAR file created at $BACKUP_DIR/demo-1.0.0-$TIMESTAMP.war"

      - name: Stop Tomcat server using PID
        run: |
          # Find the PID of the Tomcat process
          TOMCAT_PID=$(ps -ef | grep '[j]ava' | grep 'org.apache.catalina.startup.Bootstrap' | awk '{print $2}')
          
          if [ -z "$TOMCAT_PID" ]; then
            echo "Tomcat is not running."
          else
            # Kill the Tomcat process
            kill -9 $TOMCAT_PID
            echo "Tomcat server stopped. PID: $TOMCAT_PID"
          fi


    #  - name: Remove old WAR file from Tomcat server
     #   run: |
          # Remove the old WAR file from Tomcat webapps directory
      #    rm -f /home/varshini/tomcat/webapps/demo-1.0.0.war
       #   echo "Old WAR file removed from Tomcat."

      - name: Deploy new WAR file
        run: |
         # Copy the new WAR file to the Tomcat webapps directory
          cp target/*.war /home/varshini/tomcat/webapps/demo-1.0.0.war
          echo "New WAR file deployed to Tomcat."

      - name: Start Tomcat server
        run: |
          /home/varshini/tomcat/bin/startup.sh
          echo "Tomcat server started."
