name: Build and Deploy WAR to Tomcat

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build WAR
        run: mvn clean package -DskipTests

      # Step to list files in the target directory
      - name: List target directory
        run: ls -la target/

       # Step to save WAR file as an artifact
      - name: Save WAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app  # Name of the artifact
          path: target/*.war     # Path to the WAR file


      - name: Backup running WAR file
        env:
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          BACKUP_DIR="/home/varshini/war-backups" 
          mkdir -p $BACKUP_DIR

          # Remove the previous backup if it exists
          rm -f $BACKUP_DIR/demo-1.0.0-*.war

          # Define a timestamp for the new backup
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          # Backup the currently deployed WAR file from Tomcat webapps directory to the backup folder
          cp /home/varshini/tomcat/webapps/demo-1.0.0.war $BACKUP_DIR/demo-1.0.0-$TIMESTAMP.war

          echo "Backup of running WAR file created at $BACKUP_DIR/demo-1.0.0-$TIMESTAMP.war"

      - name: Remove old WAR file from Tomcat server
        env:
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          # Undeploy the old WAR file from Tomcat
          curl "http://localhost:8081/manager/text/undeploy?path=/demo-1.0.0" \
          --user $TOMCAT_USERNAME:$TOMCAT_PASSWORD
          echo "Old WAR file undeployed from Tomcat."

      - name: Deploy to Tomcat
        env:
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          WAR_FILE=$(ls target/*.war)
          curl --upload-file "$WAR_FILE" \
          "http://localhost:8081/manager/text/deploy?path=/demo-1.0.0&update=true" \
          --user $TOMCAT_USERNAME:$TOMCAT_PASSWORD
